[build]

command = "npm run production"
publish = "build_production"
functions = "./functions"

[build.environment]

PHP_VERSION = "7.2"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200