title: Settings
data:
  site_name: 'Matt Woods'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/matopher'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/matopher'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:howdy@mattwoods.io'
      icon: site/social-icons/email.svg
    -
      name: YouTube
      url: 'https://www.youtube.com/channel/UC66SdWwBo-enFmuCzrxsa1g'
      icon: site/social-icons/youtube.svg
    -
      name: LinkedIn
      url: 'https://www.linkedin.com/in/matthewchristopherwoods'
      icon: site/social-icons/linkedin.svg
  meta_image:
    - site/meta.png
