backend:
  name: git-gateway
  branch: master
media_folder: 'source/assets/img'
public_folder: '/assets/img'
media_library:
  name: cloudinary
  config:
    cloud_name: mattwoods
    api_key: getenv('CLOUDINARY_API_KEY')
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'source/_posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'extends', widget: 'hidden', default: '_layouts.post' }
      - { label: 'Section', name: 'content', widget: 'hidden', default: 'content' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Categories',
          name: 'categories',
          widget: 'select',
          options: ['marketing', 'software', 'video', 'podcast'],
          default: ['marketing'],
        }
      - { label: 'Featured Image', name: 'cover_image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'notes'
    label: 'Notes'
    folder: 'source/_notes'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'extends', widget: 'hidden', default: '_layouts.note' }
      - { label: 'Section', name: 'content', widget: 'hidden', default: 'content' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Featured Image', name: 'cover_image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Rating', name: 'rating', widget: 'number', valueType: 'int', min: 1, max: 5 }
      - { label: 'Body', name: 'body', widget: 'markdown' }
